version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: NotesDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


noteapi:
    build:
      context: ./NotesAPI
      dockerfile: Dockerfile 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=NotesDB;User=root;Password=yourpassword;"
    ports:
      - "5000:5000"
    depends_on:
      - mysql 
- 
volumes:
  mysql_data:
